### ISSUE TITLE
section reference anchors in article don't work

### ISSUE THREAD

**Issue by rofl0r** [nst/STJSON#1] opened 2016-10-28 00:31 UTC
in 7. Conclusions there are a couple hyperlinks like http://seriot.ch/json.php#6 that reference a non-existing webpage.

**Comment by nst** [comment] 2016-10-29 22:43
thank you, it's now fixed, but the issue is not related to the STJSON parser

**Closed as completed by nst** 2016-10-29 22:43 UTC

**Comment by rofl0r** [comment] 2016-10-30 11:07
that much is clear, but opening an issue here is the easiest way to contact you.
